# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_autoBWF(object):
    def setupUi(self, autoBWF):
        autoBWF.setObjectName("autoBWF")
        autoBWF.resize(926, 629)
        self.gridLayout_3 = QtWidgets.QGridLayout(autoBWF)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.titleLabel = QtWidgets.QLabel(autoBWF)
        self.titleLabel.setObjectName("titleLabel")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.titleLabel)
        self.titleLine = QtWidgets.QLineEdit(autoBWF)
        self.titleLine.setObjectName("titleLine")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.titleLine)
        self.horizontalLayout_7.addLayout(self.formLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.descriptionLabel = QtWidgets.QLabel(autoBWF)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.descriptionLabel)
        self.descriptionLine = QtWidgets.QLineEdit(autoBWF)
        self.descriptionLine.setObjectName("descriptionLine")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.descriptionLine)
        self.horizontalLayout.addLayout(self.formLayout_7)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.originatorLabel = QtWidgets.QLabel(autoBWF)
        self.originatorLabel.setObjectName("originatorLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.originatorLabel)
        self.originatorLine = QtWidgets.QLineEdit(autoBWF)
        self.originatorLine.setObjectName("originatorLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originatorLine)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.formLayout_15 = QtWidgets.QFormLayout()
        self.formLayout_15.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_15.setObjectName("formLayout_15")
        self.creationDateLine = QtWidgets.QLineEdit(autoBWF)
        self.creationDateLine.setObjectName("creationDateLine")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.creationDateLine)
        self.creationDateLabel = QtWidgets.QLabel(autoBWF)
        self.creationDateLabel.setObjectName("creationDateLabel")
        self.formLayout_15.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.creationDateLabel)
        self.horizontalLayout_12.addLayout(self.formLayout_15)
        self.gridLayout_2.addLayout(self.horizontalLayout_12, 2, 1, 1, 1)
        self.formLayout_17 = QtWidgets.QFormLayout()
        self.formLayout_17.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_17.setObjectName("formLayout_17")
        self.sourceLabel = QtWidgets.QLabel(autoBWF)
        self.sourceLabel.setObjectName("sourceLabel")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sourceLabel)
        self.sourceSelect = QtWidgets.QComboBox(autoBWF)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceSelect.sizePolicy().hasHeightForWidth())
        self.sourceSelect.setSizePolicy(sizePolicy)
        self.sourceSelect.setEditable(True)
        self.sourceSelect.setObjectName("sourceSelect")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sourceSelect)
        self.gridLayout_2.addLayout(self.formLayout_17, 2, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.originationDateLine = QtWidgets.QLineEdit(autoBWF)
        self.originationDateLine.setObjectName("originationDateLine")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originationDateLine)
        self.originationDateLabel = QtWidgets.QLabel(autoBWF)
        self.originationDateLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.originationDateLabel.setObjectName("originationDateLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.originationDateLabel)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.originationTimeLabel = QtWidgets.QLabel(autoBWF)
        self.originationTimeLabel.setObjectName("originationTimeLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.originationTimeLabel)
        self.originationTimeLine = QtWidgets.QLineEdit(autoBWF)
        self.originationTimeLine.setObjectName("originationTimeLine")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originationTimeLine)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.originatorRefLabel = QtWidgets.QLabel(autoBWF)
        self.originatorRefLabel.setObjectName("originatorRefLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.originatorRefLabel)
        self.originatorRefLine = QtWidgets.QLineEdit(autoBWF)
        self.originatorRefLine.setObjectName("originatorRefLine")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.originatorRefLine)
        self.horizontalLayout_4.addLayout(self.formLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(autoBWF)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(autoBWF)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_9.setObjectName("formLayout_9")
        self.codingHistoryLabel = QtWidgets.QLabel(self.layoutWidget)
        self.codingHistoryLabel.setObjectName("codingHistoryLabel")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.codingHistoryLabel)
        self.codingHistoryText = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.codingHistoryText.setObjectName("codingHistoryText")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.codingHistoryText)
        self.horizontalLayout_10.addLayout(self.formLayout_9)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.deckSelect = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckSelect.sizePolicy().hasHeightForWidth())
        self.deckSelect.setSizePolicy(sizePolicy)
        self.deckSelect.setEditable(False)
        self.deckSelect.setObjectName("deckSelect")
        self.gridLayout.addWidget(self.deckSelect, 0, 0, 1, 1)
        self.softwareSelect = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.softwareSelect.sizePolicy().hasHeightForWidth())
        self.softwareSelect.setSizePolicy(sizePolicy)
        self.softwareSelect.setEditable(False)
        self.softwareSelect.setObjectName("softwareSelect")
        self.gridLayout.addWidget(self.softwareSelect, 0, 1, 1, 2)
        self.adcSelect = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adcSelect.sizePolicy().hasHeightForWidth())
        self.adcSelect.setSizePolicy(sizePolicy)
        self.adcSelect.setEditable(False)
        self.adcSelect.setObjectName("adcSelect")
        self.gridLayout.addWidget(self.adcSelect, 1, 0, 1, 1)
        self.mediaSelect = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mediaSelect.sizePolicy().hasHeightForWidth())
        self.mediaSelect.setSizePolicy(sizePolicy)
        self.mediaSelect.setEditable(False)
        self.mediaSelect.setObjectName("mediaSelect")
        self.gridLayout.addWidget(self.mediaSelect, 1, 1, 1, 2)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.typeSelect = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeSelect.sizePolicy().hasHeightForWidth())
        self.typeSelect.setSizePolicy(sizePolicy)
        self.typeSelect.setEditable(False)
        self.typeSelect.setObjectName("typeSelect")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.typeSelect)
        self.gridLayout.addLayout(self.formLayout_12, 2, 0, 1, 3)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.eqSelect = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eqSelect.sizePolicy().hasHeightForWidth())
        self.eqSelect.setSizePolicy(sizePolicy)
        self.eqSelect.setEditable(False)
        self.eqSelect.setObjectName("eqSelect")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.eqSelect)
        self.gridLayout.addLayout(self.formLayout_11, 3, 0, 1, 2)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.speedSelect = QtWidgets.QComboBox(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedSelect.sizePolicy().hasHeightForWidth())
        self.speedSelect.setSizePolicy(sizePolicy)
        self.speedSelect.setEditable(False)
        self.speedSelect.setObjectName("speedSelect")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speedSelect)
        self.gridLayout.addLayout(self.formLayout_10, 3, 2, 1, 1)
        self.gridLayout_3.addWidget(self.splitter, 2, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(autoBWF)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(autoBWF)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_13.setObjectName("formLayout_13")
        self.commentLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.commentLabel.setObjectName("commentLabel")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.commentLabel)
        self.commentText = QtWidgets.QPlainTextEdit(self.layoutWidget2)
        self.commentText.setObjectName("commentText")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.commentText)
        self.horizontalLayout_11.addLayout(self.formLayout_13)
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_6.setObjectName("formLayout_6")
        self.technicianLabel = QtWidgets.QLabel(self.widget)
        self.technicianLabel.setObjectName("technicianLabel")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.technicianLabel)
        self.technicianBox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.technicianBox.sizePolicy().hasHeightForWidth())
        self.technicianBox.setSizePolicy(sizePolicy)
        self.technicianBox.setEditable(True)
        self.technicianBox.setObjectName("technicianBox")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.technicianBox)
        self.horizontalLayout_8.addLayout(self.formLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_14.setObjectName("formLayout_14")
        self.isftLabel = QtWidgets.QLabel(self.widget)
        self.isftLabel.setObjectName("isftLabel")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.isftLabel)
        self.isftSelect = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isftSelect.sizePolicy().hasHeightForWidth())
        self.isftSelect.setSizePolicy(sizePolicy)
        self.isftSelect.setEditable(True)
        self.isftSelect.setObjectName("isftSelect")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.isftSelect)
        self.verticalLayout_2.addLayout(self.formLayout_14)
        self.md5Check = QtWidgets.QCheckBox(self.widget)
        self.md5Check.setChecked(True)
        self.md5Check.setObjectName("md5Check")
        self.verticalLayout_2.addWidget(self.md5Check)
        self.gridLayout_3.addWidget(self.splitter_2, 4, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.copyrightLabel = QtWidgets.QLabel(autoBWF)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.copyrightLabel)
        self.copyrightText = QtWidgets.QPlainTextEdit(autoBWF)
        self.copyrightText.setObjectName("copyrightText")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.copyrightText)
        self.horizontalLayout_9.addLayout(self.formLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(autoBWF)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.copyrightSelect = QtWidgets.QComboBox(autoBWF)
        self.copyrightSelect.setObjectName("copyrightSelect")
        self.verticalLayout.addWidget(self.copyrightSelect)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 5, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(autoBWF)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 6, 0, 1, 1)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.md5Check.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.buttonBox.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.line.raise_()
        self.line_2.raise_()

        self.retranslateUi(autoBWF)
        self.buttonBox.accepted.connect(autoBWF.accept)
        self.buttonBox.rejected.connect(autoBWF.reject)
        QtCore.QMetaObject.connectSlotsByName(autoBWF)

    def retranslateUi(self, autoBWF):
        _translate = QtCore.QCoreApplication.translate
        autoBWF.setWindowTitle(_translate("autoBWF", "autoBWF"))
        self.titleLabel.setText(_translate("autoBWF", "Title"))
        self.descriptionLabel.setText(_translate("autoBWF", "Description"))
        self.originatorLabel.setText(_translate("autoBWF", "Originator"))
        self.creationDateLabel.setText(_translate("autoBWF", "Creation Date"))
        self.sourceLabel.setText(_translate("autoBWF", "Source"))
        self.originationDateLabel.setText(_translate("autoBWF", "OriginationDate"))
        self.originationTimeLabel.setText(_translate("autoBWF", "OriginationTime"))
        self.originatorRefLabel.setText(_translate("autoBWF", "OriginatorRef"))
        self.codingHistoryLabel.setText(_translate("autoBWF", "CodingHistory"))
        self.label_13.setText(_translate("autoBWF", "Tape type"))
        self.label_12.setText(_translate("autoBWF", "EQ"))
        self.label_7.setText(_translate("autoBWF", "Speed"))
        self.commentLabel.setText(_translate("autoBWF", "Comment"))
        self.technicianLabel.setText(_translate("autoBWF", "Technician"))
        self.isftLabel.setText(_translate("autoBWF", "ISFT"))
        self.md5Check.setText(_translate("autoBWF", "Embed MD5 of data chunk"))
        self.copyrightLabel.setText(_translate("autoBWF", "Copyright"))
        self.label_10.setText(_translate("autoBWF", "Replace with boilerplate:"))

