import argparse
import re
import xml.etree.ElementTree as ET
from os import path
from autoBWF.BWFfileIO import *


def main():
    namespaces = {"xml": "http://www.w3.org/XML/1998/namespace",
                  "pbcore": "http://www.pbcore.org/PBCore/PBCoreNamespace.html",
                  "ohms": "https://www.weareavp.com/nunncenter/ohms"}

    for ns in namespaces.keys():
        ET.register_namespace(ns, namespaces[ns])

    def qualified_element(ns, element):
        return "{{{0}}}{1}".format(namespaces[ns], element)

    def add_child(parent, element_name, element_value, attributes=None, namespace="pbcore"):
        if namespace is not None:
            element_name = qualified_element(namespace, element_name)
        if element_value != "":
            element = ET.SubElement(parent, element_name)
            element.text = element_value
            if attributes is not None:
                for attribute in attributes.keys():
                    element.set(attribute, attributes[attribute])
            return element

    def add_multivalue_child(parent, element_name, element_value, attributes=None, namespace="pbcore"):
        wikidata_regex = re.compile(r'(.+)\s+\{(Q\d+)\}')

        if element_value != "":
            items = element_value.split(';')
            for item in items:
                m = wikidata_regex.match(item)
                if m:
                    matches = m.groups()
                    name = matches[0]
                    q_code = matches[1]
                    child = add_child(parent, element_name, name,
                                      {"source": "wikidata",
                                       "ref": "https://www.wikidata.org/wiki/{}".format(q_code)}, namespace)
                else:
                    child = add_child(parent, element_name, item.strip(), namespace)

                if attributes is not None:
                    for attribute in attributes.keys():
                        child.set(attribute, attributes[attribute])

    def add_complex_child(parent, element_name, subelement_name, role_name, subelement_value, role_value):
        wikidata_regex = re.compile(r'(.+)\s+\{(Q\d+)\}')

        if subelement_value != "":
            items = subelement_value.split(';')
            for item in items:
                element = ET.SubElement(parent, element_name)
                m = wikidata_regex.match(item)
                if m:
                    matches = m.groups()
                    name = matches[0]
                    q_code = matches[1]
                    add_child(element, subelement_name, name,
                              {"source": "wikidata",
                               "ref": "https://www.wikidata.org/wiki/{}".format(q_code)})
                else:
                    add_child(element, subelement_name, item.strip())

                add_child(element, role_name, role_value)

    parser = argparse.ArgumentParser(
        description='Extract metadata from BWF and create PBCore XML, possibly incorporating into existing OHMS XML')
    parser.add_argument('infile', help="WAV file")
    args = parser.parse_args()

    infile = args.infile
    ohmsfile = args.infile.rsplit('.', 1)[0] + '_ohms.xml'
    outfile = args.infile.rsplit('.', 1)[0] + '_pbcore.xml'

    metadata = get_bwf_core(True, infile)
    metadata.update(get_bwf_tech(True, infile))
    metadata.update(get_xmp(infile, ["bwfmetaedit", "--specialchars", "--accept-nopadding"]))

    # pbcore_root = ET.Element(qualified_element("pbcore", "pbcoreDescriptionDocument"))
    pbcore_root = ET.Element("pbcoreDescriptionDocument")
    pbcore_root.append(ET.Comment('Automatically generated by bwf2pbcore. DO NOT EDIT BY HAND.'))
    pbcore_root.append(ET.Comment('To make changes, edit the internal metadata in {} and re-run bwf2pbcore'.format(infile)))

    add_child(pbcore_root, "pbcoreAssetType", metadata["form"])
    add_child(pbcore_root, "pbcoreAssetDate", metadata["ICRD"])
    add_child(pbcore_root, "pbcoreTitle", metadata["INAM"])

    add_multivalue_child(pbcore_root, "pbcoreSubject", metadata["topics"], attributes={"subjectType": "topic"})
    add_multivalue_child(pbcore_root, "pbcoreSubject", metadata["names"], {"subjectType": "name"})
    add_multivalue_child(pbcore_root, "pbcoreSubject", metadata["events"], {"subjectType": "period"})
    add_multivalue_child(pbcore_root, "pbcoreSubject", metadata["places"], {"subjectType": "geographic"})

    add_child(pbcore_root, "pbcoreDescription", metadata["xmp_description"])

    add_complex_child(pbcore_root, "pbcoreContributor", "contributor",
                      "contributorRole", metadata["interviewer"], "interviewer")
    add_complex_child(pbcore_root, "pbcoreContributor", "contributor",
                      "contributorRole", metadata["interviewee"], "interviewee")
    add_complex_child(pbcore_root, "pbcoreContributor", "contributor",
                      "contributorRole", metadata["host"], "host")
    add_complex_child(pbcore_root, "pbcoreContributor", "contributor",
                      "contributorRole", metadata["speaker"], "speaker")
    add_complex_child(pbcore_root, "pbcoreContributor", "contributor",
                      "contributorRole", metadata["performer"], "performer")

    publisher = ET.SubElement(pbcore_root, "pbcorePublisher")
    add_child(publisher, "publisher", metadata["owner"])
    add_child(publisher, "publisherRole", "copyright holder")

    instantiation = ET.SubElement(pbcore_root, "pbcoreInstantiation")
    add_child(instantiation, "instantiationDuration", metadata["Duration"].split('.')[0])
    add_child(instantiation, "instantiationLanguage", metadata["language"])

    rights = ET.SubElement(pbcore_root, "pbcoreRightsSummary")
    add_child(rights, "rightsSummary", metadata["ICOP"])

    add_child(pbcore_root, "pbcoreAnnotation", metadata["ISRC"], {"annotationType": "source collection"})

    ET.ElementTree(pbcore_root).write(outfile, xml_declaration=True)


if __name__ == '__main__':
    main()
