# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabbed.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoBWF(object):
    def setupUi(self, autoBWF):
        autoBWF.setObjectName("autoBWF")
        autoBWF.resize(1026, 600)
        self.centralwidget = QtWidgets.QWidget(autoBWF)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.guiPage = QtWidgets.QWidget()
        self.guiPage.setObjectName("guiPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.guiPage)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.guiPage)
        self.tabWidget.setObjectName("tabWidget")
        self.bwfTab = QtWidgets.QWidget()
        self.bwfTab.setObjectName("bwfTab")
        self.gridLayout = QtWidgets.QGridLayout(self.bwfTab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.descriptionLabel = QtWidgets.QLabel(self.bwfTab)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.horizontalLayout_3.addWidget(self.descriptionLabel)
        self.descriptionLine = QtWidgets.QLineEdit(self.bwfTab)
        self.descriptionLine.setObjectName("descriptionLine")
        self.horizontalLayout_3.addWidget(self.descriptionLine)
        self.descriptionSwitcher = QtWidgets.QComboBox(self.bwfTab)
        self.descriptionSwitcher.setObjectName("descriptionSwitcher")
        self.descriptionSwitcher.addItem("")
        self.descriptionSwitcher.addItem("")
        self.descriptionSwitcher.addItem("")
        self.horizontalLayout_3.addWidget(self.descriptionSwitcher)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.originatorLabel = QtWidgets.QLabel(self.bwfTab)
        self.originatorLabel.setObjectName("originatorLabel")
        self.horizontalLayout_4.addWidget(self.originatorLabel)
        self.originatorLine = QtWidgets.QLineEdit(self.bwfTab)
        self.originatorLine.setObjectName("originatorLine")
        self.horizontalLayout_4.addWidget(self.originatorLine)
        self.originatorSwitcher = QtWidgets.QComboBox(self.bwfTab)
        self.originatorSwitcher.setObjectName("originatorSwitcher")
        self.originatorSwitcher.addItem("")
        self.originatorSwitcher.addItem("")
        self.originatorSwitcher.addItem("")
        self.horizontalLayout_4.addWidget(self.originatorSwitcher)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.originatorRefLabel = QtWidgets.QLabel(self.bwfTab)
        self.originatorRefLabel.setObjectName("originatorRefLabel")
        self.horizontalLayout.addWidget(self.originatorRefLabel)
        self.originatorRefLine = QtWidgets.QLineEdit(self.bwfTab)
        self.originatorRefLine.setObjectName("originatorRefLine")
        self.horizontalLayout.addWidget(self.originatorRefLine)
        self.originatorRefSwitcher = QtWidgets.QComboBox(self.bwfTab)
        self.originatorRefSwitcher.setObjectName("originatorRefSwitcher")
        self.originatorRefSwitcher.addItem("")
        self.originatorRefSwitcher.addItem("")
        self.originatorRefSwitcher.addItem("")
        self.horizontalLayout.addWidget(self.originatorRefSwitcher)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.originationDateLabel = QtWidgets.QLabel(self.bwfTab)
        self.originationDateLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.originationDateLabel.setObjectName("originationDateLabel")
        self.horizontalLayout_6.addWidget(self.originationDateLabel)
        self.originationDateLine = QtWidgets.QLineEdit(self.bwfTab)
        self.originationDateLine.setObjectName("originationDateLine")
        self.horizontalLayout_6.addWidget(self.originationDateLine)
        self.originationDateSwitcher = QtWidgets.QComboBox(self.bwfTab)
        self.originationDateSwitcher.setObjectName("originationDateSwitcher")
        self.originationDateSwitcher.addItem("")
        self.originationDateSwitcher.addItem("")
        self.originationDateSwitcher.addItem("")
        self.horizontalLayout_6.addWidget(self.originationDateSwitcher)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.originationTimeLabel = QtWidgets.QLabel(self.bwfTab)
        self.originationTimeLabel.setObjectName("originationTimeLabel")
        self.horizontalLayout_5.addWidget(self.originationTimeLabel)
        self.originationTimeLine = QtWidgets.QLineEdit(self.bwfTab)
        self.originationTimeLine.setObjectName("originationTimeLine")
        self.horizontalLayout_5.addWidget(self.originationTimeLine)
        self.originationTimeSwitcher = QtWidgets.QComboBox(self.bwfTab)
        self.originationTimeSwitcher.setObjectName("originationTimeSwitcher")
        self.originationTimeSwitcher.addItem("")
        self.originationTimeSwitcher.addItem("")
        self.originationTimeSwitcher.addItem("")
        self.horizontalLayout_5.addWidget(self.originationTimeSwitcher)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_2)
        self.md5Check = QtWidgets.QCheckBox(self.bwfTab)
        self.md5Check.setChecked(True)
        self.md5Check.setObjectName("md5Check")
        self.verticalLayout_10.addWidget(self.md5Check)
        self.line = QtWidgets.QFrame(self.bwfTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_10.addWidget(self.line)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.codingHistoryLabel = QtWidgets.QLabel(self.bwfTab)
        self.codingHistoryLabel.setObjectName("codingHistoryLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.codingHistoryLabel)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.codingHistoryText = QtWidgets.QPlainTextEdit(self.bwfTab)
        self.codingHistoryText.setObjectName("codingHistoryText")
        self.verticalLayout_9.addWidget(self.codingHistoryText)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.codingHistorySwitcher = QtWidgets.QComboBox(self.bwfTab)
        self.codingHistorySwitcher.setObjectName("codingHistorySwitcher")
        self.codingHistorySwitcher.addItem("")
        self.codingHistorySwitcher.addItem("")
        self.codingHistorySwitcher.addItem("")
        self.horizontalLayout_20.addWidget(self.codingHistorySwitcher)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_9)
        self.horizontalLayout_21.addLayout(self.formLayout)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.deckSelect = QtWidgets.QComboBox(self.bwfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deckSelect.sizePolicy().hasHeightForWidth())
        self.deckSelect.setSizePolicy(sizePolicy)
        self.deckSelect.setEditable(False)
        self.deckSelect.setObjectName("deckSelect")
        self.verticalLayout_8.addWidget(self.deckSelect)
        self.softwareSelect = QtWidgets.QComboBox(self.bwfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.softwareSelect.sizePolicy().hasHeightForWidth())
        self.softwareSelect.setSizePolicy(sizePolicy)
        self.softwareSelect.setEditable(False)
        self.softwareSelect.setObjectName("softwareSelect")
        self.verticalLayout_8.addWidget(self.softwareSelect)
        self.adcSelect = QtWidgets.QComboBox(self.bwfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adcSelect.sizePolicy().hasHeightForWidth())
        self.adcSelect.setSizePolicy(sizePolicy)
        self.adcSelect.setEditable(False)
        self.adcSelect.setObjectName("adcSelect")
        self.verticalLayout_8.addWidget(self.adcSelect)
        self.mediaSelect = QtWidgets.QComboBox(self.bwfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mediaSelect.sizePolicy().hasHeightForWidth())
        self.mediaSelect.setSizePolicy(sizePolicy)
        self.mediaSelect.setEditable(False)
        self.mediaSelect.setObjectName("mediaSelect")
        self.verticalLayout_8.addWidget(self.mediaSelect)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_7 = QtWidgets.QLabel(self.bwfTab)
        self.label_7.setObjectName("label_7")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.speedSelect = QtWidgets.QComboBox(self.bwfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedSelect.sizePolicy().hasHeightForWidth())
        self.speedSelect.setSizePolicy(sizePolicy)
        self.speedSelect.setEditable(False)
        self.speedSelect.setObjectName("speedSelect")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.speedSelect)
        self.verticalLayout_8.addLayout(self.formLayout_10)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_12.setObjectName("formLayout_12")
        self.typeSelect = QtWidgets.QComboBox(self.bwfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typeSelect.sizePolicy().hasHeightForWidth())
        self.typeSelect.setSizePolicy(sizePolicy)
        self.typeSelect.setEditable(False)
        self.typeSelect.setObjectName("typeSelect")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.typeSelect)
        self.label_13 = QtWidgets.QLabel(self.bwfTab)
        self.label_13.setObjectName("label_13")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.verticalLayout_8.addLayout(self.formLayout_12)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_12 = QtWidgets.QLabel(self.bwfTab)
        self.label_12.setObjectName("label_12")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.eqSelect = QtWidgets.QComboBox(self.bwfTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eqSelect.sizePolicy().hasHeightForWidth())
        self.eqSelect.setSizePolicy(sizePolicy)
        self.eqSelect.setEditable(False)
        self.eqSelect.setObjectName("eqSelect")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.eqSelect)
        self.verticalLayout_8.addLayout(self.formLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.horizontalLayout_21.addLayout(self.verticalLayout_8)
        self.horizontalLayout_21.setStretch(0, 9)
        self.horizontalLayout_21.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.tabWidget.addTab(self.bwfTab, "")
        self.riffTab = QtWidgets.QWidget()
        self.riffTab.setObjectName("riffTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.riffTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titleLabel = QtWidgets.QLabel(self.riffTab)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout_2.addWidget(self.titleLabel)
        self.titleLine = QtWidgets.QLineEdit(self.riffTab)
        self.titleLine.setObjectName("titleLine")
        self.horizontalLayout_2.addWidget(self.titleLine)
        self.titleSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.titleSwitcher.setObjectName("titleSwitcher")
        self.titleSwitcher.addItem("")
        self.titleSwitcher.addItem("")
        self.titleSwitcher.addItem("")
        self.horizontalLayout_2.addWidget(self.titleSwitcher)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.creationDateLabel = QtWidgets.QLabel(self.riffTab)
        self.creationDateLabel.setObjectName("creationDateLabel")
        self.horizontalLayout_11.addWidget(self.creationDateLabel)
        self.creationDateLine = QtWidgets.QLineEdit(self.riffTab)
        self.creationDateLine.setObjectName("creationDateLine")
        self.horizontalLayout_11.addWidget(self.creationDateLine)
        self.creationDateSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.creationDateSwitcher.setObjectName("creationDateSwitcher")
        self.creationDateSwitcher.addItem("")
        self.creationDateSwitcher.addItem("")
        self.creationDateSwitcher.addItem("")
        self.horizontalLayout_11.addWidget(self.creationDateSwitcher)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.sourceLabel = QtWidgets.QLabel(self.riffTab)
        self.sourceLabel.setObjectName("sourceLabel")
        self.horizontalLayout_16.addWidget(self.sourceLabel)
        self.sourceSelect = QtWidgets.QComboBox(self.riffTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sourceSelect.sizePolicy().hasHeightForWidth())
        self.sourceSelect.setSizePolicy(sizePolicy)
        self.sourceSelect.setEditable(True)
        self.sourceSelect.setObjectName("sourceSelect")
        self.horizontalLayout_16.addWidget(self.sourceSelect)
        self.sourceSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.sourceSwitcher.setObjectName("sourceSwitcher")
        self.sourceSwitcher.addItem("")
        self.sourceSwitcher.addItem("")
        self.sourceSwitcher.addItem("")
        self.horizontalLayout_16.addWidget(self.sourceSwitcher)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.technicianLabel = QtWidgets.QLabel(self.riffTab)
        self.technicianLabel.setObjectName("technicianLabel")
        self.horizontalLayout_17.addWidget(self.technicianLabel)
        self.technicianBox = QtWidgets.QComboBox(self.riffTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.technicianBox.sizePolicy().hasHeightForWidth())
        self.technicianBox.setSizePolicy(sizePolicy)
        self.technicianBox.setEditable(True)
        self.technicianBox.setObjectName("technicianBox")
        self.horizontalLayout_17.addWidget(self.technicianBox)
        self.technicianSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.technicianSwitcher.setObjectName("technicianSwitcher")
        self.technicianSwitcher.addItem("")
        self.technicianSwitcher.addItem("")
        self.technicianSwitcher.addItem("")
        self.horizontalLayout_17.addWidget(self.technicianSwitcher)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.isftLabel = QtWidgets.QLabel(self.riffTab)
        self.isftLabel.setObjectName("isftLabel")
        self.horizontalLayout_18.addWidget(self.isftLabel)
        self.isftSelect = QtWidgets.QComboBox(self.riffTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isftSelect.sizePolicy().hasHeightForWidth())
        self.isftSelect.setSizePolicy(sizePolicy)
        self.isftSelect.setEditable(True)
        self.isftSelect.setObjectName("isftSelect")
        self.horizontalLayout_18.addWidget(self.isftSelect)
        self.isftSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.isftSwitcher.setObjectName("isftSwitcher")
        self.isftSwitcher.addItem("")
        self.isftSwitcher.addItem("")
        self.isftSwitcher.addItem("")
        self.horizontalLayout_18.addWidget(self.isftSwitcher)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.isftLabel_2 = QtWidgets.QLabel(self.riffTab)
        self.isftLabel_2.setObjectName("isftLabel_2")
        self.horizontalLayout_19.addWidget(self.isftLabel_2)
        self.iarlLine = QtWidgets.QLineEdit(self.riffTab)
        self.iarlLine.setObjectName("iarlLine")
        self.horizontalLayout_19.addWidget(self.iarlLine)
        self.iarlSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.iarlSwitcher.setObjectName("iarlSwitcher")
        self.iarlSwitcher.addItem("")
        self.iarlSwitcher.addItem("")
        self.iarlSwitcher.addItem("")
        self.horizontalLayout_19.addWidget(self.iarlSwitcher)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22.addLayout(self.verticalLayout_6)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.commentLabel = QtWidgets.QLabel(self.riffTab)
        self.commentLabel.setObjectName("commentLabel")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.commentLabel)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.commentText = QtWidgets.QPlainTextEdit(self.riffTab)
        self.commentText.setObjectName("commentText")
        self.verticalLayout_5.addWidget(self.commentText)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.commentSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.commentSwitcher.setObjectName("commentSwitcher")
        self.commentSwitcher.addItem("")
        self.commentSwitcher.addItem("")
        self.commentSwitcher.addItem("")
        self.horizontalLayout_9.addWidget(self.commentSwitcher)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_5)
        self.horizontalLayout_22.addLayout(self.formLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_8.setObjectName("formLayout_8")
        self.copyrightLabel = QtWidgets.QLabel(self.riffTab)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.copyrightLabel)
        self.copyrightText = QtWidgets.QPlainTextEdit(self.riffTab)
        self.copyrightText.setObjectName("copyrightText")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.copyrightText)
        self.horizontalLayout_7.addLayout(self.formLayout_8)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.riffTab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.copyrightSelect = QtWidgets.QComboBox(self.riffTab)
        self.copyrightSelect.setObjectName("copyrightSelect")
        self.verticalLayout.addWidget(self.copyrightSelect)
        self.copyrightSwitcher = QtWidgets.QComboBox(self.riffTab)
        self.copyrightSwitcher.setObjectName("copyrightSwitcher")
        self.copyrightSwitcher.addItem("")
        self.copyrightSwitcher.addItem("")
        self.copyrightSwitcher.addItem("")
        self.verticalLayout.addWidget(self.copyrightSwitcher)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.riffTab, "")
        self.xmpTab = QtWidgets.QWidget()
        self.xmpTab.setObjectName("xmpTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.xmpTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.sourceLabel_3 = QtWidgets.QLabel(self.xmpTab)
        self.sourceLabel_3.setObjectName("sourceLabel_3")
        self.horizontalLayout_25.addWidget(self.sourceLabel_3)
        self.formSelect = QtWidgets.QComboBox(self.xmpTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.formSelect.sizePolicy().hasHeightForWidth())
        self.formSelect.setSizePolicy(sizePolicy)
        self.formSelect.setEditable(True)
        self.formSelect.setObjectName("formSelect")
        self.horizontalLayout_25.addWidget(self.formSelect)
        self.formSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.formSwitcher.setObjectName("formSwitcher")
        self.formSwitcher.addItem("")
        self.formSwitcher.addItem("")
        self.formSwitcher.addItem("")
        self.horizontalLayout_25.addWidget(self.formSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.creationDateLabel_2 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_2.setObjectName("creationDateLabel_2")
        self.horizontalLayout_8.addWidget(self.creationDateLabel_2)
        self.languageLine = QtWidgets.QLineEdit(self.xmpTab)
        self.languageLine.setObjectName("languageLine")
        self.horizontalLayout_8.addWidget(self.languageLine)
        self.languageSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.languageSwitcher.setObjectName("languageSwitcher")
        self.languageSwitcher.addItem("")
        self.languageSwitcher.addItem("")
        self.languageSwitcher.addItem("")
        self.horizontalLayout_8.addWidget(self.languageSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.sourceLabel_2 = QtWidgets.QLabel(self.xmpTab)
        self.sourceLabel_2.setObjectName("sourceLabel_2")
        self.horizontalLayout_10.addWidget(self.sourceLabel_2)
        self.rightsOwnerSelect = QtWidgets.QComboBox(self.xmpTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightsOwnerSelect.sizePolicy().hasHeightForWidth())
        self.rightsOwnerSelect.setSizePolicy(sizePolicy)
        self.rightsOwnerSelect.setEditable(True)
        self.rightsOwnerSelect.setObjectName("rightsOwnerSelect")
        self.horizontalLayout_10.addWidget(self.rightsOwnerSelect)
        self.rightsOwnerSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.rightsOwnerSwitcher.setObjectName("rightsOwnerSwitcher")
        self.rightsOwnerSwitcher.addItem("")
        self.rightsOwnerSwitcher.addItem("")
        self.rightsOwnerSwitcher.addItem("")
        self.horizontalLayout_10.addWidget(self.rightsOwnerSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.creationDateLabel_4 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_4.setObjectName("creationDateLabel_4")
        self.horizontalLayout_13.addWidget(self.creationDateLabel_4)
        self.interviewerLine = QtWidgets.QLineEdit(self.xmpTab)
        self.interviewerLine.setObjectName("interviewerLine")
        self.horizontalLayout_13.addWidget(self.interviewerLine)
        self.interviewerSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.interviewerSwitcher.setObjectName("interviewerSwitcher")
        self.interviewerSwitcher.addItem("")
        self.interviewerSwitcher.addItem("")
        self.interviewerSwitcher.addItem("")
        self.horizontalLayout_13.addWidget(self.interviewerSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.creationDateLabel_5 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_5.setObjectName("creationDateLabel_5")
        self.horizontalLayout_14.addWidget(self.creationDateLabel_5)
        self.intervieweeLine = QtWidgets.QLineEdit(self.xmpTab)
        self.intervieweeLine.setObjectName("intervieweeLine")
        self.horizontalLayout_14.addWidget(self.intervieweeLine)
        self.intervieweeSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.intervieweeSwitcher.setObjectName("intervieweeSwitcher")
        self.intervieweeSwitcher.addItem("")
        self.intervieweeSwitcher.addItem("")
        self.intervieweeSwitcher.addItem("")
        self.horizontalLayout_14.addWidget(self.intervieweeSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.creationDateLabel_6 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_6.setObjectName("creationDateLabel_6")
        self.horizontalLayout_15.addWidget(self.creationDateLabel_6)
        self.hostLine = QtWidgets.QLineEdit(self.xmpTab)
        self.hostLine.setObjectName("hostLine")
        self.horizontalLayout_15.addWidget(self.hostLine)
        self.hostSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.hostSwitcher.setObjectName("hostSwitcher")
        self.hostSwitcher.addItem("")
        self.hostSwitcher.addItem("")
        self.hostSwitcher.addItem("")
        self.horizontalLayout_15.addWidget(self.hostSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.creationDateLabel_7 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_7.setObjectName("creationDateLabel_7")
        self.horizontalLayout_23.addWidget(self.creationDateLabel_7)
        self.speakerLine = QtWidgets.QLineEdit(self.xmpTab)
        self.speakerLine.setObjectName("speakerLine")
        self.horizontalLayout_23.addWidget(self.speakerLine)
        self.speakerSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.speakerSwitcher.setObjectName("speakerSwitcher")
        self.speakerSwitcher.addItem("")
        self.speakerSwitcher.addItem("")
        self.speakerSwitcher.addItem("")
        self.horizontalLayout_23.addWidget(self.speakerSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.creationDateLabel_8 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_8.setObjectName("creationDateLabel_8")
        self.horizontalLayout_24.addWidget(self.creationDateLabel_8)
        self.performerLine = QtWidgets.QLineEdit(self.xmpTab)
        self.performerLine.setObjectName("performerLine")
        self.horizontalLayout_24.addWidget(self.performerLine)
        self.performerSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.performerSwitcher.setObjectName("performerSwitcher")
        self.performerSwitcher.addItem("")
        self.performerSwitcher.addItem("")
        self.performerSwitcher.addItem("")
        self.horizontalLayout_24.addWidget(self.performerSwitcher)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.commentLabel_2 = QtWidgets.QLabel(self.xmpTab)
        self.commentLabel_2.setObjectName("commentLabel_2")
        self.verticalLayout_4.addWidget(self.commentLabel_2)
        self.XMPdescriptionText = QtWidgets.QPlainTextEdit(self.xmpTab)
        self.XMPdescriptionText.setObjectName("XMPdescriptionText")
        self.verticalLayout_4.addWidget(self.XMPdescriptionText)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.XMPdescriptionSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.XMPdescriptionSwitcher.setObjectName("XMPdescriptionSwitcher")
        self.XMPdescriptionSwitcher.addItem("")
        self.XMPdescriptionSwitcher.addItem("")
        self.XMPdescriptionSwitcher.addItem("")
        self.horizontalLayout_12.addWidget(self.XMPdescriptionSwitcher)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.sourceLabel_4 = QtWidgets.QLabel(self.xmpTab)
        self.sourceLabel_4.setObjectName("sourceLabel_4")
        self.horizontalLayout_26.addWidget(self.sourceLabel_4)
        self.creatorSelect = QtWidgets.QComboBox(self.xmpTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.creatorSelect.sizePolicy().hasHeightForWidth())
        self.creatorSelect.setSizePolicy(sizePolicy)
        self.creatorSelect.setEditable(True)
        self.creatorSelect.setObjectName("creatorSelect")
        self.horizontalLayout_26.addWidget(self.creatorSelect)
        self.creatorSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.creatorSwitcher.setObjectName("creatorSwitcher")
        self.creatorSwitcher.addItem("")
        self.creatorSwitcher.addItem("")
        self.creatorSwitcher.addItem("")
        self.horizontalLayout_26.addWidget(self.creatorSwitcher)
        self.verticalLayout_12.addLayout(self.horizontalLayout_26)
        self.gridLayout_4.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label = QtWidgets.QLabel(self.xmpTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_11.addWidget(self.label)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.creationDateLabel_3 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_3.setObjectName("creationDateLabel_3")
        self.horizontalLayout_27.addWidget(self.creationDateLabel_3)
        self.topicsLine = QtWidgets.QLineEdit(self.xmpTab)
        self.topicsLine.setObjectName("topicsLine")
        self.horizontalLayout_27.addWidget(self.topicsLine)
        self.topicsSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.topicsSwitcher.setObjectName("topicsSwitcher")
        self.topicsSwitcher.addItem("")
        self.topicsSwitcher.addItem("")
        self.topicsSwitcher.addItem("")
        self.horizontalLayout_27.addWidget(self.topicsSwitcher)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.creationDateLabel_10 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_10.setObjectName("creationDateLabel_10")
        self.horizontalLayout_29.addWidget(self.creationDateLabel_10)
        self.namesLine = QtWidgets.QLineEdit(self.xmpTab)
        self.namesLine.setObjectName("namesLine")
        self.horizontalLayout_29.addWidget(self.namesLine)
        self.namesSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.namesSwitcher.setObjectName("namesSwitcher")
        self.namesSwitcher.addItem("")
        self.namesSwitcher.addItem("")
        self.namesSwitcher.addItem("")
        self.horizontalLayout_29.addWidget(self.namesSwitcher)
        self.verticalLayout_11.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.creationDateLabel_11 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_11.setObjectName("creationDateLabel_11")
        self.horizontalLayout_30.addWidget(self.creationDateLabel_11)
        self.eventsLine = QtWidgets.QLineEdit(self.xmpTab)
        self.eventsLine.setObjectName("eventsLine")
        self.horizontalLayout_30.addWidget(self.eventsLine)
        self.eventsSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.eventsSwitcher.setObjectName("eventsSwitcher")
        self.eventsSwitcher.addItem("")
        self.eventsSwitcher.addItem("")
        self.eventsSwitcher.addItem("")
        self.horizontalLayout_30.addWidget(self.eventsSwitcher)
        self.verticalLayout_11.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.creationDateLabel_12 = QtWidgets.QLabel(self.xmpTab)
        self.creationDateLabel_12.setObjectName("creationDateLabel_12")
        self.horizontalLayout_31.addWidget(self.creationDateLabel_12)
        self.placesLine = QtWidgets.QLineEdit(self.xmpTab)
        self.placesLine.setObjectName("placesLine")
        self.horizontalLayout_31.addWidget(self.placesLine)
        self.placesSwitcher = QtWidgets.QComboBox(self.xmpTab)
        self.placesSwitcher.setObjectName("placesSwitcher")
        self.placesSwitcher.addItem("")
        self.placesSwitcher.addItem("")
        self.placesSwitcher.addItem("")
        self.horizontalLayout_31.addWidget(self.placesSwitcher)
        self.verticalLayout_11.addLayout(self.horizontalLayout_31)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 1, 0, 1, 2)
        self.tabWidget.addTab(self.xmpTab, "")
        self.gridLayout_8.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.guiPage)
        self.progressPage = QtWidgets.QWidget()
        self.progressPage.setObjectName("progressPage")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.progressPage)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.progressPage)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.statusLabel = QtWidgets.QLabel(self.progressPage)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout_3.addWidget(self.statusLabel)
        self.progressBar = QtWidgets.QProgressBar(self.progressPage)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.gridLayout_9.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.progressPage)
        self.gridLayout_5.addWidget(self.stackedWidget, 0, 0, 1, 1)
        autoBWF.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(autoBWF)
        self.statusbar.setObjectName("statusbar")
        autoBWF.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(autoBWF)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        autoBWF.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExport_metadata = QtWidgets.QAction(autoBWF)
        self.actionExport_metadata.setCheckable(False)
        self.actionExport_metadata.setObjectName("actionExport_metadata")
        self.actionUpdate_metadata = QtWidgets.QAction(autoBWF)
        self.actionUpdate_metadata.setCheckable(False)
        self.actionUpdate_metadata.setObjectName("actionUpdate_metadata")
        self.actionOpen = QtWidgets.QAction(autoBWF)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(autoBWF)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOpen_template = QtWidgets.QAction(autoBWF)
        self.actionOpen_template.setEnabled(True)
        self.actionOpen_template.setObjectName("actionOpen_template")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionOpen_template)
        self.toolBar.addAction(self.actionUpdate_metadata)
        self.toolBar.addAction(self.actionExport_metadata)
        self.toolBar.addAction(self.actionQuit)

        self.retranslateUi(autoBWF)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(autoBWF)

    def retranslateUi(self, autoBWF):
        _translate = QtCore.QCoreApplication.translate
        autoBWF.setWindowTitle(_translate("autoBWF", "autoBWF"))
        self.descriptionLabel.setText(_translate("autoBWF", "Description"))
        self.descriptionSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.descriptionSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.descriptionSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.originatorLabel.setText(_translate("autoBWF", "Originator"))
        self.originatorSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.originatorSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.originatorSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.originatorRefLabel.setText(_translate("autoBWF", "OriginatorRef"))
        self.originatorRefSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.originatorRefSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.originatorRefSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.originationDateLabel.setText(_translate("autoBWF", "OriginationDate"))
        self.originationDateSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.originationDateSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.originationDateSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.originationTimeLabel.setText(_translate("autoBWF", "OriginationTime"))
        self.originationTimeSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.originationTimeSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.originationTimeSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.md5Check.setText(_translate("autoBWF", "Embed MD5 of data chunk"))
        self.codingHistoryLabel.setText(_translate("autoBWF", "CodingHistory"))
        self.codingHistorySwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.codingHistorySwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.codingHistorySwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.label_7.setText(_translate("autoBWF", "Speed"))
        self.label_13.setText(_translate("autoBWF", "Tape type"))
        self.label_12.setText(_translate("autoBWF", "EQ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bwfTab), _translate("autoBWF", "BWF"))
        self.titleLabel.setText(_translate("autoBWF", "Title (INAM)"))
        self.titleSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.titleSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.titleSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel.setText(_translate("autoBWF", "Creation Date (ICRD)"))
        self.creationDateSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.creationDateSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.creationDateSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.sourceLabel.setText(_translate("autoBWF", "Source (ISRC)"))
        self.sourceSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.sourceSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.sourceSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.technicianLabel.setText(_translate("autoBWF", "Technician (ITCH)"))
        self.technicianSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.technicianSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.technicianSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.isftLabel.setText(_translate("autoBWF", "ISFT"))
        self.isftSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.isftSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.isftSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.isftLabel_2.setText(_translate("autoBWF", "Archival location (IARL)"))
        self.iarlSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.iarlSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.iarlSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.commentLabel.setText(_translate("autoBWF", "Comment (ICMT)"))
        self.commentSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.commentSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.commentSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.copyrightLabel.setText(_translate("autoBWF", "Copyright (ICOP)"))
        self.label_10.setText(_translate("autoBWF", "Replace with boilerplate:"))
        self.copyrightSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.copyrightSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.copyrightSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.riffTab), _translate("autoBWF", "RIFF"))
        self.sourceLabel_3.setText(_translate("autoBWF", "Form"))
        self.formSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.formSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.formSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_2.setText(_translate("autoBWF", "Language"))
        self.languageSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.languageSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.languageSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.sourceLabel_2.setText(_translate("autoBWF", "Copyright holder"))
        self.rightsOwnerSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.rightsOwnerSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.rightsOwnerSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_4.setText(_translate("autoBWF", "Interviewer"))
        self.interviewerSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.interviewerSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.interviewerSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_5.setText(_translate("autoBWF", "Interviewee"))
        self.intervieweeSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.intervieweeSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.intervieweeSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_6.setText(_translate("autoBWF", "Host"))
        self.hostSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.hostSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.hostSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_7.setText(_translate("autoBWF", "Speaker"))
        self.speakerSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.speakerSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.speakerSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_8.setText(_translate("autoBWF", "Performer"))
        self.performerSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.performerSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.performerSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.commentLabel_2.setText(_translate("autoBWF", "Description"))
        self.XMPdescriptionSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.XMPdescriptionSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.XMPdescriptionSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.sourceLabel_4.setText(_translate("autoBWF", "Creator"))
        self.creatorSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.creatorSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.creatorSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.label.setText(_translate("autoBWF", "Subject headings"))
        self.creationDateLabel_3.setText(_translate("autoBWF", "Topics"))
        self.topicsSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.topicsSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.topicsSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_10.setText(_translate("autoBWF", "Names"))
        self.namesSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.namesSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.namesSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_11.setText(_translate("autoBWF", "Events"))
        self.eventsSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.eventsSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.eventsSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.creationDateLabel_12.setText(_translate("autoBWF", "Places"))
        self.placesSwitcher.setItemText(0, _translate("autoBWF", "Edited"))
        self.placesSwitcher.setItemText(1, _translate("autoBWF", "Original"))
        self.placesSwitcher.setItemText(2, _translate("autoBWF", "Template"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xmpTab), _translate("autoBWF", "XMP"))
        self.label_2.setText(_translate("autoBWF", "Updating metadata. Please wait..."))
        self.statusLabel.setText(_translate("autoBWF", "TextLabel"))
        self.toolBar.setWindowTitle(_translate("autoBWF", "toolBar"))
        self.actionExport_metadata.setText(_translate("autoBWF", "Export metadata"))
        self.actionExport_metadata.setShortcut(_translate("autoBWF", "E"))
        self.actionUpdate_metadata.setText(_translate("autoBWF", "Save metadata"))
        self.actionUpdate_metadata.setShortcut(_translate("autoBWF", "S"))
        self.actionOpen.setText(_translate("autoBWF", "Open"))
        self.actionOpen.setShortcut(_translate("autoBWF", "O"))
        self.actionQuit.setText(_translate("autoBWF", "Quit"))
        self.actionQuit.setShortcut(_translate("autoBWF", "Q"))
        self.actionOpen_template.setText(_translate("autoBWF", "Load template..."))
        self.actionOpen_template.setToolTip(_translate("autoBWF", "Load template"))
        self.actionOpen_template.setShortcut(_translate("autoBWF", "T"))


